### ISSUE TITLE
Where can the official images be found

### ISSUE THREAD

**Issue by devTechi** [aws/sagemaker-tensorflow-container#123]
@nekojan 
I don't know where I can find you official images to add some different libraries which we can use in SageMaker.

In https://github.com/aws/sagemaker-tensorflow-container/issues/43#issuecomment-393710684_) you wrote that you publish them for publicly use. But where can I find them? :) 

> The instructions on this repository are focused on how to build the official SageMaker docker images. However, for normal use, you don't need to do this as we publish official versions that are publically available for use. Mostly, this would be useful if you want to change the code or dependencies in the image.

Because building from scratch takes a real long time and needs some memory adjustments for the docker building environment etc. This takes me a long time to figure out. Perhaps that could be added in the README file?

Thanks you.

Greetz
André

**Comment by yangaws** [comment]
Hi @devTechi ,

I am not sure if I get your question. I guess you are looking for the public official SageMaker TensorFlow container that you could just pull?

The official image is in following format:
520713654638.dkr.ecr.{region_name}.amazonaws.com/sagemaker-tensorflow:{tensorflow_version}-{processor}-{python_version}

For example, if you want the cpu image in us-east-1 with tensorflow 1.11.0 in python 2. The image is:

520713654638.dkr.ecr.us-east-1.amazonaws.com/sagemaker-tensorflow:1.11.0-cpu-py2

For current supported versions, please refer to README (https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst#tensorflow-sagemaker-estimators)

Thanks

**Comment by devTechi** [comment]
Hi @yangaws 
thanks for you answer. That was exactly what I was looking for.

Did I miss those information or where could I have found them?

Anyways yes. I want to use the already built images from you ECR or another registry without the need to build them on our own. This is really time consuming and needed adjustments in the local docker preferences (at least on my mac).

So this was really helpful. Given that we can close this issue, but may I suggest that you add this really important information to the README.md or another documentation on aws?

Kind regrads
André
