### ISSUE TITLE
[Question] TF 1.12 timeline

### ISSUE THREAD

**Issue by zmjjmz** [aws/sagemaker-tensorflow-container#136]
Hey there,

I've encountered a weird bug in using entrypoints built around the surprisingly unsupported Keras -> `model_to_estimator` -> `train_and_evaluate` process where the `global_step` count doesn't increment during training, causing Sagemaker to take the untrained model as the final one. 

This issue is resolved in TF 1.12 afaict (I was able to replicate it locally in TF 1.11 but not TF 1.12), however the latest version of the Sagemaker tensorflow containers is still 1.11. Is there an ETA on TF 1.12 containers? 

Thanks!

**Comment by jesterhazy** [comment]
This is a priority for us too. Stay tuned!
