### ISSUE TITLE
Error in tensorflor_model_server

### ISSUE THREAD

**Issue by juanilarregui** [aws/sagemaker-tensorflow-container#154]
Hi,

I have a custom Tensorflow Model running in SageMaker (with my own `input_fn` and `output_fn` to handle pickled input-output). After a couple of working request/response from outside, at some point a new request can't be served, with error (in log):

`Error in 'tensorflow_model_server': double free or corruption (fasttop): 0x00007ff740179300 ***`

After that error, any posterior request won't be served, saying:

`#011status = StatusCode.UNAVAILABLE`
```
#011debug_error_string = "
{
    "created": "@1547930893.297227189",
    "description": "Failed to create subchannel",
    "file": "src/core/ext/filters/client_channel/client_channel.cc",
    "file_line": 2261,
    "referenced_errors": [
        {
            "created": "@1547930893.297223127",
            "description": "Pick Cancelled",
            "file": "src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc",
            "file_line": 245,
            "referenced_errors": [
                {
                    "created": "@1547930893.297200588",
                    "description": "Connect Failed",
                    "file": "src/core/ext/filters/client_channel/subchannel.cc",
                    "file_line": 867,
                    "grpc_status": 14,
                    "referenced_errors": [
                        {
                            "created": "@1547930893.297198188",
                            "description": "OS Error",
                            "errno": 97,
                            "file": "src/core/lib/iomgr/socket_utils_common_posix.cc",
                            "file_line": 379,
                            "os_error": "Address family not supported by protocol",
                            "syscall": "socket",
                            "target_address": "[::1]:14000"
                        }
                    ]
                }
            ]
        }
    ]
}
```

After that, the only way to get the model predicting again is by removing the endpoint and deploying the model with a new one.

I've seen that a possible workaround is doing:
```
sudo apt-get install libtcmalloc-minimal4
export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"
```
but, of course, that actions are not possible in SageMaker.
Hope you can help.

**Comment by juanilarregui** [comment]
Hi @mvsusp ,

It seems correct.

System Information
Framework: TensorFlow
Framework Version: 1.12
Python Version: python 2.7
CPU or GPU: CPU
Python SDK Version: 1.17.2
Are you using a custom image: No.

Describe the problem
I can correctly deploy a custom TensorFlow Model using the python SDK (using sagemaker.tensorflow.TensorFlowModel, etc.). The first (or few) predictions are correctly served. After that, it gives the error indicated in "Minimal repro / logs". The endpoint is still "In Service", but the predictions can not be served anymore.

Minimal repro / logs
The first time, it gives the next error (one time, subsequent errors are reproduced below):

`Error in 'tensorflow_model_server': double free or corruption (fasttop): 0x00007ff740179300 `

and no more predictions can be served (ever). The endpoint is still "In Service". Ping to the endpoint get a 200 response, as can be seen in the log. However, internally, the predictions can not be served anymore. The subsequent errors I get in each prediction are something like:

```
#011status = StatusCode.UNAVAILABLE
#011debug_error_string = "
{
    "created": "@1547930893.297227189",
    "description": "Failed to create subchannel",
    "file": "src/core/ext/filters/client_channel/client_channel.cc",
    "file_line": 2261,
    "referenced_errors": [
        {
            "created": "@1547930893.297223127",
            "description": "Pick Cancelled",
            "file": "src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc",
            "file_line": 245,
            "referenced_errors": [
                {
                    "created": "@1547930893.297200588",
                    "description": "Connect Failed",
                    "file": "src/core/ext/filters/client_channel/subchannel.cc",
                    "file_line": 867,
                    "grpc_status": 14,
                    "referenced_errors": [
                        {
                            "created": "@1547930893.297198188",
                            "description": "OS Error",
                            "errno": 97,
                            "file": "src/core/lib/iomgr/socket_utils_common_posix.cc",
                            "file_line": 379,
                            "os_error": "Address family not supported by protocol",
                            "syscall": "socket",
                            "target_address": "[::1]:14000"
                        }
                    ]
                }
            ]
        }
    ]
}
```

Do you know when this could be fixed? I have a deadline to deploy the prediction model, and I need to know if I can trust SageMaker to deploy it or search for another solution, maybe my own Docker container.

Thank you very much.

**Comment by mvsusp** [comment]
Hi @juanilarregui,

Thanks for the detailed information. Do you have a minimal model that we can use to reproduce the issue? That can accelerate the fix.

In the meanwhile you could extend the container as follow:

- create a Dockerfile using the original TFS container as base 
- install your dependency on the file
- push to your own ECS account
- deploy the container with using the [``image_name`` optional argument, pointing to your own image](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/README.rst#sagemakertensorflowtensorflow-class). 

Thanks again!

**Comment by juanilarregui** [comment]
Hi @mvsusp ,

Unfortunately, I'm not allowed to provide a model. In the meanwhile, we are going for the ECS solution with our own container.

Hope to see the fix soon.

Thanks!

**Comment by icywang86rui** [comment]
@juanilarregui 
Did using tcmelloc fix the problem?

**Comment by icywang86rui** [comment]
Haven't heard back for a few days. Closing. Feel free to reopen if the work around doesn't fix the problem.
