### ISSUE TITLE
1.9.0 docker build fails

### ISSUE THREAD

**Issue by sermolin** [aws/sagemaker-tensorflow-container#162]
sh-4.2$ docker build -t tensorflow-final:1.9.0-cpu-py2 -f Dockerfile.cpu .
Sending build context to Docker daemon  51.16MB
Step 1/17 : FROM ubuntu:16.04
 ---> 7e87e2b3bf7a
Step 2/17 : MAINTAINER Amazon AI
 ---> Using cache
 ---> a8a720b08874
Step 3/17 : ARG framework_installable
 ---> Using cache
 ---> 0f83c4349ed3
Step 4/17 : ARG framework_support_installable=sagemaker_tensorflow_container-1.0.0.tar.gz
 ---> Using cache
 ---> 3397dfad634e
Step 5/17 : WORKDIR /root
 ---> Using cache
 ---> 15aeae3cf54b
Step 6/17 : COPY $framework_installable .
 ---> f385113d5903
Step 7/17 : COPY $framework_support_installable .
COPY failed: stat /var/lib/docker/tmp/docker-builder905262005/sagemaker_tensorflow_container-1.0.0.tar.gz: no such file or directory

I tried following the instructions and downloaded the correct wheel file. New command failed with the same error message:
sh-4.2$ docker build -t tensorflow-final:1.9.0-cpu-py2 --build-arg framework_installable=tensorflow-1.9.0-cp27-cp27mu-manylinux1_x86_64.whl -f Dockerfile.cpu .
......
Step 7/17 : COPY $framework_support_installable .
COPY failed: stat /var/lib/docker/tmp/docker-builder211768317/sagemaker_tensorflow_container-1.0.0.tar.gz: no such file or directory

**Comment by icywang86rui** [comment]
@sermolin,
Apart from downloading the tensorflow binary you will also need to build sagemaker_tensorflow_container and copy the tar ball to the dockerfile directory

```
# Create the SageMaker TensorFlow Container Python package.
cd sagemaker-tensorflow-containers
python setup.py sdist

#. Copy your Python package to “final” Dockerfile directory that you are building.
cp dist/sagemaker_tensorflow_container-<package_version>.tar.gz docker/<tensorflow_version>/final/py2
```
Hope this helps.
