### ISSUE TITLE
missing value for `framework_support_installable`?

### ISSUE THREAD

**Issue by domino14** [aws/sagemaker-tensorflow-container#182]
Hi, I am trying to use the script-mode Dockerfile here: https://github.com/aws/sagemaker-tensorflow-container/blob/script-mode/docker/1.12.0/Dockerfile.gpu

I tried to build it as the docs showed in the README. For example:

```docker build -t sagemaker-py3-tf12-base:latest --build-arg py_version=3 --build-arg framework_installable=tensorflow_gpu-1.12.0-cp36-cp36m-manylinux1_x86_64.whl -f Dockerfile.base .```  The framework_installable came from a download from the pypi site, for tf version 1.12. The docker build fails at this step:

```
Step 25/28 : COPY $framework_support_installable .
COPY failed: stat /var/lib/docker/tmp/docker-builder388360514/sagemaker_tensorflow_container-2.0.0.tar.gz: no such file or directory
```

Notice I didn't provide a value for `framework_support_installable` as this was not specified in the docs. What value should I provide? Where did this file come from?

**Comment by laurenyu** [comment]
hi @domino14, thanks for using SageMaker! Apologies for the confusing documentation - the README in this repository hasn't been updated yet for Script Mode.

to get the binary for `framework_support_installable`, run `python setup.py sdist` in the root directory of this repository, and then copy `dist/sagemaker_tensorflow_container-2.0.0.tar.gz` into the directory with the Dockerfile that you're using for building.

**Comment by domino14** [comment]
@laurenyu thank you for your help. I seem to have successfully built the sagemaker container now, although I got this error (or warning?) a couple of times:

```
sagemaker-tensorflow-container 2.0.0 has requirement sagemaker-containers>=2.4.4, but you'll have sagemaker-containers 2.4.2 which is incompatible.
```

**Comment by laurenyu** [comment]
@domino14 can you try running `pip install -U sagemaker-containers` before running `python setup.py sdist`?

**Comment by domino14** [comment]
Hi @laurenyu, that didn't fix it, but the container still seemed to build.

However, when I try to train on this container, using Sagemaker, I get the following error in Cloudwatch:

```
2019-04-23 13:53:06.231738: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

2019-04-23 13:53:06.242609: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: UNKNOWN ERROR (-1)

2019-04-23 13:53:06.243380: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: aws

2019-04-23 13:53:06.243403: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: aws

2019-04-23 13:53:06.243530: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program

2019-04-23 13:53:06.243600: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 396.37.0
```

Do you know what the problem could be here? All I did was build the tensorflow-gpu image as I mentioned above, and added my training code to it, but it can't do `cuInit` so it uses CPU training which is much slower.

**Comment by laurenyu** [comment]
@domino14 hmm. out of curiosity, is there something missing from the image that's motivating you to build it yourself rather than using the pre-built SageMaker image? if you can use the pre-built one, does doing so produce the same error?

**Comment by domino14** [comment]
@laurenyu, I don't know how to use the pre-built one. Where can I find it? I found something that said the pre-built images are at this hardcoded URL:

`520713654638.dkr.ecr.us-west-2.amazonaws.com` but it's asking me for basic auth credentials when I use any path after it (for example `docker pull 520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-tensorflow-scriptmode:1.12.0-gpu-py3`) gives me an error

**Comment by laurenyu** [comment]
@domino14 if you're using the [SageMaker Python SDK](https://github.com/aws/sagemaker-python-sdk) to launch your training job, then the SDK will take care of figuring out the image name. If you're using boto3 or some other client, then you have the correct URI - `520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-tensorflow-scriptmode:1.12.0-gpu-py3`. You shouldn't need to pull it locally to use it in SageMaker; SageMaker will take care of downloading it as part of a training job.

**Comment by domino14** [comment]
@laurenyu I am building a docker image so that I can add my own training code to it. For example, my Dockerfile now looks like (if I am trying to use the default SageMaker image):

```
FROM 520713654638.dkr.ecr.us-east-1.amazonaws.com/sagemaker-tensorflow:1.12.0-gpu-py3

COPY . /opt/program

ENV PYTHONUNBUFFERED=TRUE
ENV PATH="/opt/program:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/cuda-9.0/targets/x86_64-linux/lib:/usr/local/cuda-9.0/targets/x86_64-linux/lib/stubs:/usr/lib/x86_64-linux-gnu/:${LD_LIBRARY_PATH}"
WORKDIR /opt/program
```
Then in my `/opt/program` directory there is a `train` executable that starts the python script to do the training. But this fails because it can't download the Docker image above (the base path). Before this, I tried using the Docker image that I created myself based on this repo, but I got those libcuda errors.. 

I was using boto3 to try to create a training job, but I need to give it a path to the Docker image. If I give it the default hardcoded path above, how do I make it use my training algorithm?

**Comment by laurenyu** [comment]
@domino14 got it. to download the image, you'll need to authenticate with ECR:

```bash
$(aws ecr get-login --no-include-email --registry-ids 520713654638)
```

as for exposing your program, if you set the environment variable `SAGEMAKER_PROGRAM=/opt/program`, that should allow the underlying sagemaker-tensorflow-container support code to find your training code. You may also need to set `SAGEMAKER_SUBMIT_DIRECTORY` to the directory where your code is located.

**Comment by domino14** [comment]
Hi @laurenyu, I used the command you gave me above to download the default sagemaker image. I downloaded this one: `520713654638.dkr.ecr.us-east-1.amazonaws.com/sagemaker-tensorflow-scriptmode:1.12.0-gpu-py3`. My own docker image then extends from it by adding the code, as in the Dockerfile I pasted above. Then I start a SageMaker training job with this new image. I get the same error:

```
2019-04-23 20:24:05.955662: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: UNKNOWN ERROR (-1)
2019-04-23 20:24:05.956163: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: aws
2019-04-23 20:24:05.956177: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: aws
2019-04-23 20:24:05.956251: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
2019-04-23 20:24:05.956332: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 396.37.0
```

**Comment by domino14** [comment]
@laurenyu  thanks so much for your help, I got it working! I removed the `ENV LD_LIBRARY_PATH` lines from the Dockerfile as I assumed the SageMaker host would have everything set up properly.
