### ISSUE TITLE
Is there any documentation to build the SageMaker Elastic Inference TensorFlow serving container for python 3?

### ISSUE THREAD

**Issue by ghost** [aws/sagemaker-tensorflow-container#206]

**Comment by ChoiByungWook** [comment]
Please visit this repo: https://github.com/aws/sagemaker-tensorflow-serving-container#building-your-image

This may require changes on how you call your predictions, as the repo above interacts with the TensorFlow serving REST API.

There aren't any plans to support Python 3 in the TensorFlow container, which utilizes GRPC to make the predictions.

Please let me know if there is anything I can clarify.

Thanks!
