### ISSUE TITLE
Script mode with code build?

### ISSUE THREAD

**Issue by leolorenzoluis** [aws/sagemaker-tensorflow-container#225]
Is it possible to use script mode for continuous deployment or it's only for local development?

**Comment by laurenyu** [comment]
hi @leolorenzoluis, could you elaborate on what you're looking to do? The TensorFlow Script Mode images are available publicly via Amazon ECR.

**Comment by leolorenzoluis** [comment]
@laurencer I figured it out. It was just hard to find the public ECR images in the documentation.
