### ISSUE TITLE
botocore version error

### ISSUE THREAD

**Issue by Elizaaaaa** [aws/sagemaker-tensorflow-container#244]
https://github.com/aws/sagemaker-tensorflow-container/blob/e3a7a6581d93997ea4890074e145e42fed0d9801/setup.py#L60

When i run sagemaker test with `pytest test/integration/sagemaker` , it returns me with the error 
ContextualVersionConflict: (botocore 1.13.0 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('botocore<1.13.0,>=1.12.72'), set(['boto3']))

After checking logs i found out the botocore installed here is 1.13.0. is it possible to set it to <1.13.0,>=1.12.72? I tested with botocore==1.12.195, all sagemaker tests passed.

Thanks!

**Comment by laurenyu** [comment]
what package in your workspace was requiring botocore<.13.0,>=1.12.72?

If you have a pre-installed version of botocore that satisfies >=1.12.140, then `pip install .[test]` shouldn't try and upgrade botocore.

**Comment by Elizaaaaa** [comment]
> what package in your workspace was requiring botocore<.13.0,>=1.12.72?
> 
> If you have a pre-installed version of botocore that satisfies >=1.12.140, then `pip install .[test]` shouldn't try and upgrade botocore.

checked the boto3 version and resolve the problem. thanks!
