### ISSUE TITLE
Support for bleeding edge versions of Tensorflow

### ISSUE THREAD

**Issue by durandg12** [aws/sagemaker-tensorflow-container#246]
Hi,

I am thinking about using SageMaker for research purposes and I need to use the latest tools released with the last version of TF.

Yet, TensorFlow 2.0.0 has been released [more than 1 month ago](https://github.com/tensorflow/tensorflow/releases/tag/v2.0.0) and it seems that there is still no support for it. 

So I wonder : what is the timeframe of AWS for releasing the newer versions of the most popular Deep Learning frameworks?

Knowing that the delay can be as long as a month makes me worry about using SageMaker at all.

As a side note (I don't need it, but it should also be noted), TensorFlow 1.15.0 has been released [20 days ago](https://github.com/tensorflow/tensorflow/releases/tag/v1.15.0) and it also seems missing from the supported frameworks.

I just opened [the same issue](https://github.com/aws/sagemaker-python-sdk/issues/1115) in the [sagemaker-python-sdk repo](https://github.com/aws/sagemaker-python-sdk) because I felt the SDK and the Dockerfiles of this repo were sufficiently distinct objects to have their own issue each, feel free to close this one if that is not the case.

**Comment by anankira** [comment]
Thank you for your interest ! We plan to add support for Tensorflow 1.15 and Tensorflow 2.0. Stay tuned!

**Comment by 00krishna** [comment]
+1 for Tensorflow 2.0 support. It really makes no sense for me to start using Sagemaker when trying to build custom containers requires more effort than just building up an EC2 node from the deeplearning AMI. I really appreciate your work on releasing a Tensorflow 2.0 container. Do you have any time-frame on that. Or do you know of any github repos where someone has created a custom Tensorflow 2.0.0 gpu container?

**Comment by laurenyu** [comment]
For an example of how to build your own custom TF 2.0 image for use with SageMaker, see https://docs.aws.amazon.com/sagemaker/latest/dg/build-container-to-train-script-get-started.html

For the base image, you can use `tensorflow/tensorflow:2.0.0b1`, per [this StackOverflow question](https://stackoverflow.com/questions/57396212/sagemaker-and-tensorflow-2-0).

**Comment by 00krishna** [comment]
Thanks so much @laurenyu that is great. This will help a lot. I was reading through some of the dockerfile code in the repo trying to figure out how to adapt it. The links you gave will help a ton. Thanks so much.

**Comment by 00krishna** [comment]
I thought I would check if there are any updates to Tensorflow 2.0 availability in advance of the AWS conference next week? Are they planning any new releases of the containers? Thanks.

**Comment by laurenyu** [comment]
Unfortunately we have no roadmap to share at this time. Thank you for your patience!

**Comment by Eladio** [comment]
Is there any on news on TF 2.0 support?

**Comment by surajkota** [comment]
Thank you for using Sagemaker
Tensorflow-1.15 was released earlier this month. Tensorflow-2.0 containers have also been released 3 days ago.
