### ISSUE TITLE
RuntimeError: Failed to run: ['docker-compose', '-f', '/tmp/tmp93Sn5U/docker-compose.yaml', 'up', '--build', '--abort-on-container-exit'], Process exited with code: 127

### ISSUE THREAD

**Issue by starrylive** [aws/sagemaker-tensorflow-container#263]
SageMaker deploy Tensorflow container,but can't work !
![image](https://user-images.githubusercontent.com/38621156/71576025-1211d200-2b2a-11ea-9f76-ada682f094cd.png)
![image](https://user-images.githubusercontent.com/38621156/71576068-42f20700-2b2a-11ea-89ef-e491f40b3001.png)

**Comment by ChuyangDeng** [comment]
Hi @starrylive, Thanks for using SageMaker. From the screenshot it seems you are using a customized image "sagemaker-tf-cifar-10-example:latest" and the code failed at training stage. Can you provide us with more details of the image you are using?

e.g. which framework version you are using? which python version you are using? etc.

**Comment by starrylive** [comment]
Hi @ChuyangDeng, thanks for bringing this to our attention.  I'm trying to run the awsLab notebook. I don't modify the example from the awsLab.  the URL is https://github.com/awslabs/amazon-sagemaker-examples/tree/master/advanced_functionality/tensorflow_bring_your_own

**Comment by laurenyu** [comment]
where are you running this? (i.e. SageMaker Notebook Instance, locally on your computer, etc.)

**Comment by starrylive** [comment]
> where are you running this? (i.e. SageMaker Notebook Instance, locally on your computer, etc.)
SageMaker Notebook Instance.

**Comment by laurenyu** [comment]
I just ran the notebook without issue on a fresh SageMaker Notebook Instance.

What kernel and instance type are you using?

**Comment by starrylive** [comment]
> I just ran the notebook without issue on a fresh SageMaker Notebook Instance.
> 
> What kernel and instance type are you using?

I used to Tensorflow2 kernel and tensorlfow3 kernel . I just  used python2 kernel and  I finished the training job inerrantly. In my opinion, kernel version can influence the training job.

**Comment by tbass134** [comment]
I get this issue when running locally. The only way to fix is to restart the notebook instance, which is really annoying

**Comment by pietrobolcato** [comment]
@tbass134 if you're still having this issue, I found a solution that avoid starting over the notebook kernel. You need to stop the docker container, i.e, running:

`docker ps`

To get the ID of the running container, and then

`docker stop <CONTAINER-ID>`

This will enable the cell to run again
