### ISSUE TITLE
Submodule Error

### ISSUE THREAD

**Issue by larsll** [aws/sagemaker-tensorflow-container#345]
The submodule setup of this repository is not clean. When running `git submodule status` one gets the error message `fatal: no submodule mapping found in .gitmodules for path 'benchmarks/tf_benchmarks/benchmarks`.

Using the module directly this might not be a major issue; using it as a submodule somewhere causes issues in processes that recursively updates submodules...

**Comment by laurenyu** [comment]
sorry for the delayed response here - I've opened a PR (#349) to address this.

**Comment by laurenyu** [comment]
@larsll PR has been merged. do you still see the error when updating your submodule?

**Comment by larsll** [comment]
@laurenyu -- it looks good! No error messages now.

**Comment by laurenyu** [comment]
great, glad to hear it!
