### ISSUE TITLE
Out of Sync with sagemaker-containers

### ISSUE THREAD

**Issue by mrb114** [aws/sagemaker-tensorflow-container#45]
It appears that this repository is out of sync with sagemaker-containers v2.0.2. Are there any plans to update this repository for those changes and if so what is the timeline?

**Comment by yangaws** [comment]
Hi @mrb114 ,

We have plans for migrating current tensorflow container (mxnet as well) to sagemaker-containers v2. Recently we will discuss the priority and timeline for this. Updates will be brought to this issue when related decisions are made.

For now, is using the old version sagemaker-container a problem for you? If you have any problems or concerns, please bring them here. We may provide short term work-around. And your feedbacks will be super helpful for us to plan and prioritize the migration!

Thanks for using SageMaker!

**Comment by VladimirEI** [comment]
In line 5 in Dockerfile.cpu there is empty reference, I guess it should point to local tar.gz of sagemaker-containers:
`ARG framework_installable`

It does not build the image without it, so I tried to install it directly from PYPI. The container image was built OK, though I haven't tested for version compatibility:

```
# Use local version of image built from Dockerfile.cpu in /docker/1.6.0/base
FROM tensorflow-base:1.6.0-cpu-py2
MAINTAINER Amazon AI

# ARG framework_installable
ARG framework_support_installable=sagemaker_tensorflow_container-1.0.0.tar.gz

WORKDIR /root

# Will install from pypi once packages are released there. For now, copy from local file system.
# COPY $framework_installable .
COPY $framework_support_installable .

# RUN framework_installable_local=$(basename $framework_installable) && \
RUN framework_support_installable_local=$(basename $framework_support_installable) && \
    \
#    pip install framework_installable_local && \
    pip install sagemaker-containers && \
    pip install $framework_support_installable_local && \
    \
#    rm $framework_installable_local && \
    rm $framework_support_installable_local

# entry.py comes from sagemaker-container-support
ENTRYPOINT ["entry.py"]
```

**Comment by laurenyu** [comment]
The TensorFlow Script Mode images rely on v2 of sagemaker-containers. Check out the code here: https://github.com/aws/sagemaker-tensorflow-container/tree/script-mode
