### ISSUE TITLE
Can we have dockerfiles for python 3 

### ISSUE THREAD

**Issue by yshvrdhn** [aws/sagemaker-tensorflow-container#50]

**Comment by nadiaya** [comment]
Hi @yshvrdhn 

Thanks for your interest in SageMaker! Support for python3 is definitively important! This is on our backlog, and we'll give you an update when we have an ETA.

Related issue: https://github.com/aws/sagemaker-python-sdk/issues/19

**Comment by yyolk** [comment]
+1

**Comment by Christiaanvv** [comment]
+1

**Comment by elgalu** [comment]
Hi, what's the status of this?

```
docker pull 520713654638.dkr.ecr.eu-central-1.amazonaws.com/sagemaker-tensorflow:1.11.0-gpu-py2
#=> pulling ...
```

```
docker pull 520713654638.dkr.ecr.eu-central-1.amazonaws.com/sagemaker-tensorflow:1.11.0-gpu-py3
#=> sagemaker-tensorflow:1.11.0-gpu-py3 not found
```

**Comment by xinshang-iai** [comment]
+1 please support python 3.6

**Comment by laurenyu** [comment]
hey all, apologies for not updating this issue sooner. Python 3 is now supported with the SageMaker TensorFlow Script Mode images. They come with a different training script format that allows for more flexibility, in addition to supporting Python 3.6.

For more:
* docs: https://sagemaker.readthedocs.io/en/stable/using_tf.html#preparing-a-script-mode-training-script
* code: https://github.com/aws/sagemaker-tensorflow-container/tree/script-mode
* ECR URI format: `520713654638.dkr.ecr.<region>.amazonaws.com/sagemaker-tensorflow-scriptmode:1.12.0-<cpu|gpu>-py3`
