### ISSUE TITLE
Build GPU docker image within AWS - Best practices

### ISSUE THREAD

**Issue by PedroCardoso** [aws/sagemaker-tensorflow-container#53]
Hi.

I want to do my custom docker image using GPU. Unfortunately, I do not have a local GPU to run nvidia-docker, and I was wonder if you guys have some best practices to build it ?

My idea was to build it on a GPU EC2 instance. But not sure that would work .

**Comment by iquintero** [comment]
Hi

@PedroCardoso You can build your images without using nvidia-docker. nvidia-docker is only required for runtime. Let me know if this doesnt work for you.

**Comment by PedroCardoso** [comment]
ok, thanks
