### ISSUE TITLE
Error on entry.py

### ISSUE THREAD

**Issue by PedroCardoso** [aws/sagemaker-tensorflow-container#60]
I have created a custom image for Tensorflow 

The custom image have a slight change in training and addes pip install for several packages to make it faster start.

While running I just got now this error :

```
Traceback (most recent call last):
File "/usr/local/bin/entry.py", line 12, in <module>
cs.configure_logging()
```
As I have no `entry.py` or `configure_logging()` in my code, I am guessing this is internal to Sagemaker.

**Comment by yangaws** [comment]
Hi @PedroCardoso ,

Could we have more info on how you run your container including:

1, What were you trying to do with your container? How did you do that?
2, Is what you post here the full stack trace? Do you have more logs for this?

**Comment by PedroCardoso** [comment]
Hi @yangaws 

I was using an AWS containers as base, and did some changes on the training class. Nothing external that would change the container behaviour. 
I have a CPU and a GPU compilation. The CPU one is running fine, but not the GPU.

The full log is this : 
```
ERROR:root:uncaught exception: 'module' object has no attribute 'configure_logging'
Traceback (most recent call last):
  File "/usr/local/bin/entry.py", line 12, in <module>
    cs.configure_logging()
AttributeError: 'module' object has no attribute 'configure_logging'```

I can give you a reference for the image being used as well as the training job in private
