### ISSUE TITLE
Unable to save assets

### ISSUE THREAD

**Issue by zjost** [aws/sagemaker-tensorflow-container#72]
The model exporter seems to be defined [here](https://github.com/aws/sagemaker-tensorflow-container/blob/master/src/tf_container/trainer.py#L130-L131).  There seems to not be a way to define the `assets_extra` parameter, as describe in the TensorFlow [docs](https://www.tensorflow.org/api_docs/python/tf/estimator/LatestExporter).

This is a problem since models sometimes need [vocabulary files](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file) or [embedding weights](https://forums.aws.amazon.com/thread.jspa?messageID=833063&tstart=0).

There are ways around this for training (i.e. see the most recent link) by using a data channel, but this still fails for batch transforms or predicts since tensorflow is looking in the asset directory of the export.  This leads to a failure like the following:
```
2018-09-11 21:23:46.419683: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at lookup_table_init_op.cc:145 : Not found: /opt/ml/model/export/Servo/1536196112/assets/vocab.txt; No such file or directory
```

To fix this, could we allow the user to specify in their parameter list and extract, like is done [here](https://github.com/aws/sagemaker-tensorflow-container/blob/master/src/tf_container/trainer.py#L137)?

**Comment by winstonaws** [comment]
We've gotten a lot of feedback about the limitations of our current interface, and customers not being able to control all of the relevant options. We're working on changing the interface for the Tensorflow Container to allow for more flexibility in general (think something along the lines of https://github.com/aws/sagemaker-pytorch-container ), which should solve your problem. Until then, we likely won't invest any dev effort to making fixes to the current interface, unfortunately. If you need to be unblocked urgently, you could consider creating your own fork and building your own image using the instructions here: https://github.com/aws/sagemaker-tensorflow-container#building-your-image

**Comment by laurenyu** [comment]
The TensorFlow Script Mode images now allow for greater flexibility with training scripts, as Winston alluded to. You can read more about that here: https://sagemaker.readthedocs.io/en/stable/using_tf.html#preparing-a-script-mode-training-script
