### ISSUE TITLE
README not correct for tensorflow >= 1.9.0

### ISSUE THREAD

**Issue by zjost** [aws/sagemaker-tensorflow-container#73]
The README says all are built from base image, but that seems to no longer be the case.  1.9.0 reference "framework_support_installable", but this is not mentioned in the instructions.  Is this the location of `dist/sagemaker_tensorflow_container-<package_version>.tar.gz`?

**Comment by yangaws** [comment]
Hi @zjost,

Sorry for the inconvenience. We did update the README in time. From 1.9.0 on, base docker file is not required. We will update the README soon.
