### ISSUE TITLE
Need the customized exporter fn supported in tf container

### ISSUE THREAD

**Issue by chinazm** [aws/sagemaker-tensorflow-container#75]
in this line:
https://github.com/aws/sagemaker-tensorflow-container/blob/d442ac7ecd87507c30378c98fcb36ebb9b585849/src/tf_container/trainer.py#L128

we need to add to support the customized exporter:
  **if hasattr(self.customer_script, 'exporter_fn'):
            # We may want to add the ability for the user to customize their exporter name in the future.
            # Should only be relevant for use cases outside of SageMaker Hosting,
            # or if we add support for multiple models.
            exporter = self.customer_script.exporter_fn('Servo', self.customer_params)
  elif self.saves_training():
            serving_input_receiver_fn = lambda: 
            self.customer_script.serving_input_fn(self.customer_params)
            exporter = tf.estimator.LatestExporter('Servo',
                                                   serving_input_receiver_fn=serving_input_receiver_fn)
else:
            logger.warn('Neither exporter_fn nor serving_input_fn specified, model NOT saved, ' +
                        'use checkpoints to reconstruct')
            exporter = None**

**Comment by mvsusp** [comment]
Hello @chinazm 

Thanks for your suggestion. We are in the process of redesigning the SageMaker TensorFlow Container with the objective to improve the customer experience. One of the objectives is allow out customers to define their own exporter. 

I will close ticket, please feel free, to reopen to ask additional questions or submit a new ticket.

Thanks for using SageMaker!
