### ISSUE TITLE
export_saved_model do not copy asset files

### ISSUE THREAD

**Issue by lukasz-artificial** [aws/sagemaker-tensorflow-container#99]
A TensorFlow model seems to have directory structure as follows:
```
/assets/
/assets/vocabulary.txt
/variables/
/variables/variables.data-00000-of-00001
/variables/variables.index
/saved_model.pb
```

Current implementation of `export_saved_model` copy only `saved_model.pb`
file and `variables/variables*` files and do not copy asset files.

**Comment by jesterhazy** [comment]
fixed in pending PR #100
